# Common stuff

theme:
  name: 'material'
  logo: 'assets/images/frescobaldi.svg'
  feature:
    tabs: true
markdown_extensions:
#  - codehilite:
#      guess_lang: false
  - admonition
  - toc:
      permalink: true
use_directory_urls: false
extra:
  search:
    tokenizer: '[\s\-\.]+'
  social:
    - type: 'github'
      link: 'https://github.com/openlilylib'
    - type: 'wordpress'
      link: 'http://lilypondblog.org'
plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized
repo_url: https://github.com/uliska/lilyponds-scheme/

# Subbook specific stuff
site_dir: ../site/introduction
edit_uri: edit/master/introduction/docs
site_name: LilyPond's Scheme
nav:
  - Introduction:
    - Home: index.md
    - "LilyPond's Scheme": 'lilyponds-scheme.md'
    - Challenges:
      - 'Learning the Language': 'language.md'
      - 'Integrating in LilyPond': 'integrating.md'
      - 'Advanced Interaction': 'advanced.md'
  - 'Scheme':
    - Home: '../scheme/index.html'
  - 'Scheme in LilyPond':
    - Home: '../lilypond/index.html'
  - 'LilyPond Internals':
    - Home: '../internals/index.html'
