# Common stuff

theme:
  name: 'material'
  palette:
    primary: 'Deep Purple'
    accent: 'Deep Purple'
  feature:
    tabs: true
markdown_extensions:
  - codehilite:
      guess_lang: false
  - admonition
  - toc:
      permalink: true
extra:
  search:
    tokenizer: '[\s\-\.]+'
  social:
    - type: 'github'
      link: 'https://github.com/openlilylib'
    - type: 'wordpress'
      link: 'http://lilypondblog.org'
plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized
use_directory_urls: false
site_dir: '../site/lilypond'
repo_url: https://github.com/uliska/lilyponds-scheme/
edit_uri: edit/master/lilypond/docs
site_name: Scheme in LilyPond
nav:
  - Introduction:
    - Home: '../introduction/index.html'
  - 'Scheme':
    - Home: '../scheme/index.html'
  - 'Scheme in LilyPond':
    - Home: 'index.md'
    - 'Switching Between Scheme and LilyPond': 'functions/switch-languages.md'
    - 'Music, Scheme and Void Functions': 'functions/music-scheme-void.md'
    - 'Interface of the functions': 'functions/interface.md'
    - 'Markup Functions': 'functions/markup-functions.md'
    - 'Creating Lists of Music Expressions': 'functions/list-music-expressions.md'
    - 'Old Stuff':
      - 'Writing Music Functions': 'old-stuff/functions/README.md'
      - 'Getting to Grips with Scheme in LilyPond': 'old-stuff/functions/01.md'
      - 'Start Doing Something Useful': 'old-stuff/functions/02.md'
      - 'Reusing Code': 'old-stuff/functions/03.md'
      - 'Recursion': 'old-stuff/functions/04.md'
  - 'LilyPond Internals':
    - Home: '../internals/index.html'
